"""Add posts and comments

Revision ID: 5cd8ed458194
Revises: 1bb4372daa38
Create Date: 2026-05-02 13:54:47.334795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd8ed458194'
down_revision: Union[str, None] = '1bb4372daa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowing_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowing_rates',
    sa.Column('series_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('period', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('series_key', 'period', name=op.f('borrowing_rates_pkey'))
    )
    # ### end Alembic commands ###
